CREATE TABLE PLAYER(
      ID INT NOT NULL AUTO_INCREMENT,
      IDSTEAM VARCHAR(12) NOT NULL,
      PSEUDO VARCHAR(40) NOT NULL,
      NBMATCHS INT NOT NULL,
      NBFRAGS INT NOT NULL,
      LASTUPDATE LONG NOT NULL,
      MOYFRAGS DOUBLE(5,1) NOT NULL,
      MOYDMG DOUBLE(6,2) NOT NULL,
      MOYAIR DOUBLE(2,2) NOT NULL,
      PRIMARY KEY(ID)
)
ENGINE=INNODB;

